import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const [post, setPost] = useState([]);

  useEffect(() => {
    axios.get("/api/prismaFindMany").then((response) => {
      setPost(response.data);
    });
  }, []);

  return (
    <>
      <Head>
        <title>Application Excercise</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          {post.map((element, index, array) => (
            <div key={index}>
              <h2 className="font-bold">{element.title}</h2>
              <p>{element.body}</p>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
