import axios from "axios";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [blah, setBlah] = useState("initialBlah");

  const fetchX = async () => {
    const x = await axios.get("/api/hello");
    setBlah(x.data.message);
  };

  fetchX()

  return (
    <>
      <Head>
        <title>Application Excercise</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {blah}
      </main>
    </>
  );
}
